services:
  - type: web
    name: biblioteca-backend
    runtime: docker
    repo: https://github.com/jorgemartia/ProyectoMVCSpringBOOT-Biblioteca-Jorge-Martinez_Douglas-Pacheco
    branch: develop
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
