services:
  - type: web
    name: biblioteca-backend
    runtime: docker
    repo: https://github.com/jorgemartia/ProyectoMVCSpringBOOT-Biblioteca-Jorge-Martinez_Douglas-Pacheco
    branch: develop
    dockerfilePath: biblioteca3/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://containers-us-west-153.railway.app:6331/railway
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: hT1v0k3Jz4fX7bWz9U4I
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.MySQL8Dialect
