services:
  - name: proyecto-biblioteca
    type: web
    env: docker
    branch: main
    autoDeploy: true
    plan: free
    dockerfilePath: Dockerfile
    # healthCheckPath: "/api/libros"  # descomenta si tu app tiene este endpoint

databases:
  - name: biblioteca-db
    databaseName: db_biblioteca
    user: biblio_user
    plan: free